# Generated by Django 2.0.5 on 2018-06-04 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('slug', models.SlugField(max_length=150)),
                ('category', models.CharField(choices=[('ROM', 'Romance'), ('THR', 'Thriller'), ('MYS', 'Mystery'), ('LIF', 'Life'), ('DRA', 'Drama'), ('HIS', 'Historic'), ('BIO', 'Biography'), ('KID', 'Kids')], default='ROM', max_length=3)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_written', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
