# Generated by Django 2.0.5 on 2018-06-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
