# Generated by Django 2.0.5 on 2018-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180609_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug_chapter',
            field=models.SlugField(default='aaa', max_length=150),
            preserve_default=False,
        ),
    ]
