# Generated by Django 2.0.5 on 2018-06-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_chapter_nr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['nr']},
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='text',
        ),
    ]
