# Generated by Django 2.0.5 on 2018-06-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_dialog_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['nr']},
        ),
        migrations.AddField(
            model_name='text',
            name='nr',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
