# Generated by Django 2.0.5 on 2018-06-19 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20180613_2052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='nr',
        ),
        migrations.RemoveField(
            model_name='text',
            name='nr',
        ),
    ]
