# Generated by Django 2.0.5 on 2018-07-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_chapter_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='slug_chapter',
            new_name='slug',
        ),
    ]
